org.gradle.jvmargs=-Xmx3g -Djava.net.preferIPv4Stack=true
kotlin.daemon.jvmargs=-Djava.net.preferIPv4Stack=true
android.useAndroidX=true
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=8899
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=8899
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.https.nonProxyHosts=localhost|127.0.0.1
