pluginManagement {
    repositories {
        maven { url = uri("file:///home/hatch/workspace/.tooling/localrepo") }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = uri("file:///home/hatch/workspace/.tooling/localrepo") }
    }
}
rootProject.name = "WorkoutTracker"
include(":app")
